import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/Footer";
import Navbar from "./Components/Navbar/Navbar";
import EllipseRing from "./Components/Hero/Ellipse/EllipseRing";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative w-full h-screen overflow-x-hidden bg-nft-navy-blue">
          <Navbar />
          <>
            <EllipseRing />
          </>
          {children}
          {/* <Footer /> */}
        </main>
      </body>
    </html>
  );
}
